### ISSUE TITLE
Inconsistent output

### ISSUE THREAD

**Issue by phaazon** [chpatrick/haskell-hidapi#4]
I just compared with `node-hid`, and the output of `enumerateAll` is just wrong. I think I’m going to patch it. :)

**Comment by chpatrick** [comment]
Can you give an example?

**Comment by phaazon** [comment]
![](http://i.imgur.com/Z9Ps3BU.png)

**Comment by phaazon** [comment]
After looking to the code, I decided to write my own binding from scratch.

**Comment by chpatrick** [comment]
Could you still point out what's wrong exactly?
