### ISSUE TITLE
Building the library fails with ghc 7.10.1 on osx el capitan and windows 10

### ISSUE THREAD

**Issue by cfscholl** [chpatrick/haskell-hidapi#5]
Thanks for making this library ! I have  used it to control a robot (MBot) from within Haskell. Unfortunately the library as is wouldn't compile on my mac nor on windows 10. I had to make two tiny adjustments. 

System/HIDAPI.hsc            =>  import Control.DeepSeq 
hidapi.cabal                         => deepseq    >= 0.1 (in the build-depends)

It would be great if you could either make these changes or explain me how the library could be installed without having to make these changes. Otherwise I will have to re-distributed your code with the super tiny patch.  

Just to be complete here is the error I get without the changes:

> $ cabal install 
...
Configuring hidapi-0.1.3...
Building hidapi-0.1.3...
Preprocessing library hidapi-0.1.3...
[1 of 1] Compiling System.HIDAPI    ( dist/build/System/HIDAPI.hs, dist/build/System/HIDAPI.o )

>System/HIDAPI.hsc:95:10:
    Not in scope: type constructor or class ‘NFData’
    Perhaps you meant ‘Data’ (imported from Data.Data)

>System/HIDAPI.hsc:126:10:
    Not in scope: type constructor or class ‘NFData’
    Perhaps you meant ‘Data’ (imported from Data.Data)
Failed to install hidapi-0.1.3
cabal: Error: some packages failed to install:
hidapi-0.1.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by nh2** [comment]
This should be fixed by #6. Please reopen in case it isn't.
