### ISSUE TITLE
Build error on certain versions of depencies

### ISSUE THREAD

**Issue by fegu** [chpatrick/haskell-hidapi#6]
Building on a fresh Haskell install of ghc 7.6.3 we get deepseq-generics-0.2.0.0 (due to lax constraint of hidapi). This results in missing NFData (see below). Simply commenting out the two offending lines works fine (albeit without NFData instances). Another suggestion: Linux needs libudev-dev installed as well as just udev. Perhaps libudev-dev should be added as a requirement. Not everyone will know to install libudev-dev when install fails with error missing udev.

cabal install hidapi
Resolving dependencies...
Configuring hidapi-0.1.3...
Building hidapi-0.1.3...
Failed to install hidapi-0.1.3
Build log ( /home/pi/.cabal/logs/hidapi-0.1.3.log ):
Configuring hidapi-0.1.3...
Building hidapi-0.1.3...
Preprocessing library hidapi-0.1.3...
[1 of 1] Compiling System.HIDAPI    ( dist/build/System/HIDAPI.hs, dist/build/System/HIDAPI.o )

System/HIDAPI.hsc:94:10:
    Not in scope: type constructor or class `NFData'
    Perhaps you meant `Data' (imported from Data.Data)

System/HIDAPI.hsc:125:10:
    Not in scope: type constructor or class `NFData'
    Perhaps you meant `Data' (imported from Data.Data)
cabal: Error: some packages failed to install:
hidapi-0.1.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by nh2** [comment]
@chpatrick I can do this one tomorrow; `deepseq-generics-0.2.0.0` removed the `NFData` reexport.

**Comment by nh2** [comment]
I've pushed a commit that should fix it.

I've tried it on Linux with the following variants of `stack.yaml`:

```
resolver: lts-2.22
```

```
resolver: lts-2.22

extra-deps:
  - deepseq-generics-0.2.0.0
```

```
resolver: lts-5.17
```

@fegu Please reopen if it's not fixed for you. I'll upload the fix to hackage now.

**Comment by nh2** [comment]
> Another suggestion: Linux needs libudev-dev installed as well as just udev. Perhaps libudev-dev should be added as a requirement. Not everyone will know to install libudev-dev when install fails with error missing udev.

We already have `extra-libraries: udev` in the cabal file (I believe that's what you were referring to); I've just pushed a commit in addition that mentions that debian-like distributions split off the `-dev` packages.

@fegu Do you think that makes it clear enough?

**Comment by nh2** [comment]
Uploaded: https://hackage.haskell.org/package/hidapi-0.1.4

**Comment by fegu** [comment]
Works perfectly, thanks.
